### ISSUE TITLE
Failed to build with (<$>) not in scope

### ISSUE THREAD

**Issue by afcowie** [aloiscochard/machines-io#3]
**machines-io** is failing to build on GHC 7.8.4, as follows:

```
Building machines-io-0.2.0.4...
Preprocessing library machines-io-0.2.0.4...
[1 of 1] Compiling System.IO.Machine ( src/System/IO/Machine.hs, dist/dist-sandbox-106a5a35/build/System/IO/Machine.o )

src/System/IO/Machine.hs:22:27: Not in scope: ‘<$>’

src/System/IO/Machine.hs:25:26: Not in scope: ‘<$>’
cabal: Error: some packages failed to install:
machines-io-0.2.0.4 failed during the building phase. The exception was:
ExitFailure 1
```

I'm going to have a guess that you're on 7.10 and that they're including Control.Applicative in prelude now? Anyway, failed trying to build **codex**.

AfC

**Comment by aloiscochard** [comment]
Shame, I did enable `-Wall` (and aggressively fix warnings) and upgraded to 7.10 at the same time... that was a mistake, as I did not notice that I removed some critical import for 7.8.

Fixed in `0.2.0.7` with conditional import for 7.8, also I guess you came here because you wanted to get codex to compile, I had to fix it as well:
https://hackage.haskell.org/package/codex-0.3.0.4

Thanks for the quick report!
